{{- range $i, $endpoint := .Values.endpoints }}
{{- if $endpoint.security.enabled }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: acl-folder-endpoint-{{ $i }}
data:
{{- range $fname, $content := $endpoint.security.aclFiles }}
  {{ $fname }}: |
{{ $content | indent 4 }}
{{- end }}

---
{{- end }}
{{- end }}