apiVersion: v1
kind: ConfigMap
metadata:
  name: basyx-realm
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  basyx-realm.json: |-
{{- (.Files.Get "config/basyx-realm.json") | nindent 4 }}