apiVersion: v1
kind: ConfigMap
metadata:
  name: fa3st-realm
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  fa3st.json: |-
{{- (.Files.Get "config/fa3st.json") | nindent 4 }}
