apiVersion: v1
kind: Secret
metadata:
  name: mongodb-auth
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.auth.rootUser | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.auth.rootPassword | quote }}