{{- if .Values.rabbitmq.ingress.certManager.enabled }}
{{- $secretName := (index .Values.rabbitmq.ingress.extraTls 0).secretName }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-rabbitmq-tls
  labels:
    app.kubernetes.io/name: rabbitmq-mqtt
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  secretName: {{ $secretName }}
  issuerRef:
    name: {{ .Values.rabbitmq.ingress.certManager.clusterIssuer | default "letsencrypt-prod" }}
    kind: ClusterIssuer
  dnsNames:
    {{- range .Values.rabbitmq.ingress.extraTls }}
    {{- range .hosts }}
    - {{ . }}
    {{- end }}
    {{- end }}
{{- end }}