apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-realm
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  rabbitmq.json: |-
{{- (.Files.Get "config/rabbitmq.json") | nindent 4 }}
