apiVersion: v2
name: umbrella-rabbitmq-aas
description: A Helm chart for AAS deployment with RabbitMQ messaging
dependencies:
  - name: faaast-service
    version: 0.2.0
    repository: "file://../faaast-service"
  - name: faaast-registry
    version: 0.2.1
    repository: "file://../faaast-registry"
  - name: aas-basyx-v2-full
    version: 2.1.11
    repository: "https://eclipse-basyx.github.io/charts/"
  - name: mongodb
    version: 0.6.1
    repository: "oci://registry-1.docker.io/cloudpirates"
    # version: 18.1.1
    # repository: "https://charts.bitnami.com/bitnami"
    alias: mongodb
    condition: mongodb.enabled
  - name: rabbitmq
    version: 0.1.1
    repository: "oci://registry-1.docker.io/cloudpirates"
    # version: 16.0.14
    # repository: "https://charts.bitnami.com/bitnami"

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.6.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.1"
