name: AsyncAPI documents processing

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Remove git folder
        run: rm -rf .git

      - name: Move frontpage
        run: mv .github/resources/index.html .

      - name: Generating HTML for AAS document
        uses: asyncapi/cli@v3.2.0
        with:
          template: '@asyncapi/html-template@2.3.14'
          filepath: specs/asyncapi_spec_aas.yaml
          output: aas-repository

      - name: Generating HTML for Submodels document
        uses: asyncapi/cli@v3.2.0
        with:
          template: '@asyncapi/html-template@2.3.14'
          filepath: specs/asyncapi_spec_submodel.yaml
          output: submodel-repository

      - name: Generating HTML for SubmodelElements document
        uses: asyncapi/cli@v3.2.0
        with:
          template: '@asyncapi/html-template@2.3.14'
          filepath: specs/asyncapi_spec_submodelelement.yaml
          output: submodel-repository-submodelelement

      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: generate
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4